"""New field in interaction

Revision ID: 0f5257914b2e
Revises: 2e33c2b4b93d
Create Date: 2024-12-17 16:42:08.239002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5257914b2e'
down_revision: Union[str, None] = '2e33c2b4b93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction', sa.Column('watchtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction', 'watchtime')
    # ### end Alembic commands ###
