"""add user fields

Revision ID: 2191b0b0f246
Revises: a0f95b6eb567
Create Date: 2024-12-09 20:57:20.916537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from services.user import bcrypt_context

# revision identifiers, used by Alembic.
revision: str = '2191b0b0f246'
down_revision: Union[str, None] = 'a0f95b6eb567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('sex', sa.String(), nullable=True))
    op.add_column('User', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # insert admin user with password 'qwerty' and role 'ROLE_ADMIN'
    op.execute(f"""
            INSERT INTO "User" (username, hashed_password, role) VALUES (
                'admin', '{bcrypt_context.hash("qwerty")}', 'ROLE_ADMIN'
            );
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'role')
    op.drop_column('User', 'sex')
    op.drop_column('User', 'birth_date')
    # ### end Alembic commands ###
