"""Cascade deleting was set for auth

Revision ID: 3659f38c3ef5
Revises: b748d2b71a2f
Create Date: 2024-12-26 11:06:10.197347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3659f38c3ef5'
down_revision: Union[str, None] = 'b748d2b71a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interaction_profile_id_fkey', 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profile_auth_id_fkey', 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'auth', ['auth_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recommend_profile_id_fkey', 'recommend', type_='foreignkey')
    op.create_foreign_key(None, 'recommend', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reply_profile_id_fkey', 'reply', type_='foreignkey')
    op.create_foreign_key(None, 'reply', 'profile', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.create_foreign_key('reply_profile_id_fkey', 'reply', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    op.create_foreign_key('recommend_profile_id_fkey', 'recommend', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key('profile_auth_id_fkey', 'profile', 'auth', ['auth_id'], ['id'])
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key('interaction_profile_id_fkey', 'interaction', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###
