"""Foreign key was added

Revision ID: 7ed42d610c69
Revises: 1629c8e97bfa
Create Date: 2024-12-25 21:31:48.353829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed42d610c69'
down_revision: Union[str, None] = '1629c8e97bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recommend', 'film', ['film_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    # ### end Alembic commands ###
