"""Added new table for replies and deleted file path and ebals

Revision ID: 82044e6c5f08
Revises: 0f5257914b2e
Create Date: 2024-12-20 12:26:47.990556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82044e6c5f08'
down_revision: Union[str, None] = '0f5257914b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('film', 'file_path')
    op.drop_column('profile', 'ebals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('ebals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('film', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('reply')
    # ### end Alembic commands ###
