"""new recommend table

Revision ID: b61465636915
Revises: 82044e6c5f08
Create Date: 2024-12-21 17:15:59.091494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from services.user import bcrypt_context


# revision identifiers, used by Alembic.
revision: str = 'b61465636915'
down_revision: Union[str, None] = '82044e6c5f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('film_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(f"""
            INSERT INTO "auth" (id, login, hashed_password, role) VALUES (
                    0, 'admin', '{bcrypt_context.hash("passwd")}', 'ROLE_ADMIN'
               ); 
        """)
    op.execute(f"""
            INSERT INTO "profile" (id, auth_id) VALUES (
                    0, 0
               );
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommend')
    # ### end Alembic commands ###
