"""Cascade deleting was set

Revision ID: b748d2b71a2f
Revises: 7ed42d610c69
Create Date: 2024-12-25 23:33:58.605498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b748d2b71a2f'
down_revision: Union[str, None] = '7ed42d610c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interaction_film_id_fkey', 'interaction', type_='foreignkey')
    op.create_foreign_key(None, 'interaction', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('recommend_film_id_fkey', 'recommend', type_='foreignkey')
    op.create_foreign_key(None, 'recommend', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reply_film_id_fkey', 'reply', type_='foreignkey')
    op.create_foreign_key(None, 'reply', 'film', ['film_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.create_foreign_key('reply_film_id_fkey', 'reply', 'film', ['film_id'], ['id'])
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    op.create_foreign_key('recommend_film_id_fkey', 'recommend', 'film', ['film_id'], ['id'])
    op.drop_constraint(None, 'interaction', type_='foreignkey')
    op.create_foreign_key('interaction_film_id_fkey', 'interaction', 'film', ['film_id'], ['id'])
    # ### end Alembic commands ###
