"""Added age rating field

Revision ID: c0e4fa01ba34
Revises: 8c3974acd11a
Create Date: 2024-12-15 12:18:46.836304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e4fa01ba34'
down_revision: Union[str, None] = '8c3974acd11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('age_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'age_rating')
    # ### end Alembic commands ###
